acm:
  enabled: false
acmpca:
  enabled: false
apigateway:
  enabled: false
apigatewayv2:
  enabled: false
applicationautoscaling:
  enabled: false
athena:
  enabled: false
bedrock:
  enabled: false
bedrockagent:
  enabled: false
bedrockagentcorecontrol:
  enabled: false
cloudfront:
  enabled: false
cloudtrail:
  enabled: false
cloudwatch:
  enabled: false
cloudwatchlogs:
  enabled: false
codeartifact:
  enabled: false
cognitoidentityprovider:
  enabled: false
documentdb:
  enabled: false
dynamodb:
  enabled: false
ec2:
  enabled: false
ecr:
  enabled: false
ecrpublic:
  enabled: false
ecs:
  enabled: false
efs:
  enabled: false
eks:
  enabled: false
elasticache:
  enabled: false
elbv2:
  enabled: false
emrcontainers:
  enabled: false
eventbridge:
  enabled: false
iam:
  enabled: false
kafka:
  enabled: false
keyspaces:
  enabled: false
kinesis:
  enabled: false
kms:
  enabled: false
lambda:
  enabled: false
memorydb:
  enabled: false
mq:
  enabled: false
networkfirewall:
  enabled: false
opensearchservice:
  enabled: false
organizations:
  enabled: false
pipes:
  enabled: false
prometheusservice:
  enabled: false
ram:
  enabled: false
rds:
  enabled: false
recyclebin:
  enabled: false
route53:
  enabled: false
route53resolver:
  enabled: false
s3:
  enabled: false
s3control:
  enabled: false
sagemaker:
  enabled: false
secretsmanager:
  enabled: false
ses:
  enabled: false
sfn:
  enabled: false
sns:
  enabled: false
sqs:
  enabled: false
ssm:
  enabled: false
wafv2:
  enabled: false
